### ISSUE TITLE
Marbles demo for v0.6 fabric ?

### ISSUE THREAD

**Issue by likepunk** [IBM-Blockchain-Archive/marbles#38]
Hello, is there marbles demo available for version 0.6.1 of the fabric?

I tried to use it with IBM provided docker-compose fabric(v0.6.1) and getting following error...it seems it requires good amount of app code changes and was curious if anyone had updates yet.

Thanks,

loading hardcoded users
[ibc-js] Peer:  vp0-vp0...:1443
[ibc-js] Registering  vp0-vp0...:1443  w/enrollId - test_user1
[ibc-js] Registration success x1 : test_user1
[ibc-js] removing temp dir
[ibc-js] Downloading zip
redirect... https://codeload.github.com/IBM-Blockchain/marbles-chaincode/zip/master
[ibc-js] Downloading zip
[ibc-js] Unzipping zip
[ibc-js] Unzip done
[ibc-js] Scanning files [ 'part2_chaincode.go' ]
[ibc-js] Parsing file for shim version
[ibc-js] Found shim version: github.com/hyperledger/fabric/core/chaincode/shim
[ibc-js] Parsing file for invoke functions - part2_chaincode.go
[ibc-js] Found cc invoke function:  init
[ibc-js] Found cc invoke function:  delete
[ibc-js] Found cc invoke function:  write
[ibc-js] Found cc invoke function:  init_marble
[ibc-js] Found cc invoke function:  set_user
[ibc-js] Found cc invoke function:  open_trade
[ibc-js] Found cc invoke function:  perform_trade
[ibc-js] Found cc invoke function:  remove_trade
[ibc-js] Parsing file for query functions - part2_chaincode.go
[ibc-js] Found cc query function:  read
[ibc-js] load_chaincode() finished
[ibc-js] Deploy Chaincode - Starting
[ibc-js]        function: init , arg: [ '99' ]

         Waiting...

         deploy resp error - there is no chaincode hash name in response: { jsonrpc: '2.0',
  error:
   { code: -32001,
     message: 'Deployment failure',
     data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code \'go get\' failed with error: "exit status 2"\n# github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2\n/opt/gopath/_usercode_/556595698/src/github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2/part2_chaincode.go:67: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:\n\t*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)\n\t\thave Init(*shim.ChaincodeStub, string, []string) ([]byte, error)\n\t\twant Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)\n' },
  id: 1478501361330 }
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error no cc name',
  code: 502,
  details:
   { jsonrpc: '2.0',
     error:
      { code: -32001,
        message: 'Deployment failure',
        data: 'Error when deploying chaincode: Error getting chaincode package bytes: Error getting code \'go get\' failed with error: "exit status 2"\n# github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2\n/opt/gopath/_usercode_/556595698/src/github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2/part2_chaincode.go:67: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:\n\t*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)\n\t\thave Init(*shim.ChaincodeStub, string, []string) ([]byte, error)\n\t\twant Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)\n' },
     id: 1478501361330 }
 peers:<ID:<name:"vp0" > address:"172.19.0.2:7051" type:VALIDATOR >
vp0_1         | 06:49:31.274 [devops] getChaincodeBytes -> ERRO 140 Error getting chaincode package bytes: Error getting code 'go get' failed with error: "exit
vp0_1         | # github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2
vp0_1         | /opt/gopath/_usercode_/556595698/src/github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2/part2_chaincode.go:67: cannot use new(SimpleCode) as type shim.Chaincode in argument to shim.Start:
vp0_1         |         *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp0_1         |                 have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp0_1         |                 want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp0_1         | 06:49:31.274 [devops] Deploy -> ERRO 141 Error deploying chaincode spec: type:GOLANG chaincodeID:<path:"https://github.com/ibm-blockchain/marble" > ctorMsg:<args:"init" args:"99" > secureContext:"test_user1"
vp0_1         |
vp0_1         |  error: Error getting chaincode package bytes: Error getting code 'go get' failed with error: "exit status 2"
vp0_1         | # github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2
vp0_1         | /opt/gopath/_usercode_/556595698/src/github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2/part2_chaincode.go:67: cannot use new(SimpleCode) as type shim.Chaincode in argument to shim.Start:
vp0_1         |         *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp0_1         |                 have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp0_1         |                 want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp0_1         | 06:49:31.274 [rest] processChaincodeDeploy -> ERRO 142 Error when deploying chaincode: Error getting chaincode package bytes: Error getting code"exit status 2"
vp0_1         | # github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2
vp0_1         | /opt/gopath/_usercode_/556595698/src/github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2/part2_chaincode.go:67: cannot use new(SimpleCode) as type shim.Chaincode in argument to shim.Start:
vp0_1         |         *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
vp0_1         |                 have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
vp0_1         |                 want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
vp0_1         | 06:49:31.274 [rest] ProcessChaincode -> INFO 143 REST successfully deploy chaincode: {"jsonrpc":"2.0","error":{"code":-32001,"message":"Deploymen deploying chaincode: Error getting chaincode package bytes: Error getting code 'go get' failed with error: \"exit status 2\"\n# github.com/ibm-blockchain/marbt2\n/opt/gopath/_usercode_/556595698/src/github.com/ibm-blockchain/marbles-chaincode/hyperledger/part2/part2_chaincode.go:67: cannot use new(SimpleChaincode) (t shim.Chaincode in argument to shim.Start:\n\t*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)\n\t\thave Init(*shim.ChaincodeStuberror)\n\t\twant Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)\n"},"id":1478501361330}
vp1_1         | 06:49:33.324 [peer] ensureConnected -> DEBU 0c4 Touch service indicates no dropped connections

**Comment by dshuffma-ibm** [comment]
When working with fabric `0.6.x` you need to use the [branch v2.0](https://github.com/IBM-Blockchain/marbles/tree/v2.0). that one contains the correct chaincode changes

**Comment by likepunk** [comment]
Thanks David! Does it work with 0.6.1 as well? I just tried for local Docker-compose fabric and getting some errors...thanks again!

**Comment by dshuffma-ibm** [comment]
it should be working with 0.6.1. I just updated the master and v2.0 branch to work with a docker-compose setup by default (instead of a bluemix setup). ie its using a different credentials file called  `mycreds.docker_compose.json`.  you will likely have to tweak this file to your network. meaning replace the `api_host` and `api_port` and `users` with settings for your network.

**Comment by likepunk** [comment]
Thanks David. 
Do you know if something just changed to git zip file for v2.0? it was working fine until this morning, but from an hour ago when I download it it gives an error saying it can't find 'part2' directory....

blockchain:~/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode # l
total 36
drwxr-xr-x  2 root root  4096 Nov  7 14:56 ./
drwxr-xr-x 10 root root  4096 Nov  7 14:56 ../
-rw-rw-rw-  1 root root 25127 Nov  7 15:04 marbles_chaincode.go
blockchain:~/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode # cd /root/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode/part2
-bash: cd: /root/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode/part2: No such file or directory
blockchain:~/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode #

------------------------------------------ Server Up - localhost:3000 ------------------------------------------
Running using Developer settings
- Tracking Deployment
  loading hardcoded peers
  loading hardcoded users
  [ibc-js] Peer:  vp0-vp0...:1443
  [ibc-js] Registering  vp0-vp0...:1443  w/enrollId - test_user1
  [ibc-js] Registration success x1 : test_user1
  [ibc-js] Downloading zip
  redirect... https://codeload.github.com/IBM-Blockchain/marbles/zip/v2.0
  [ibc-js] Downloading zip
  [ibc-js] Unzipping zip
  [ibc-js] Unzip done
  [ibc-js] Scanning files undefined
  **_! [ibc-js] fs readdir Error { [Error: ENOENT, scandir '/root/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode/part2']_**
  errno: -2,
  code: 'ENOENT',
  path: '/root/ibm/node/marbles-demos/marbles-four/marbles/node_modules/ibm-blockchain-js/temp/unzip/marbles-2.0/chaincode/part2' }
  ! [ibc-js] Error -  did not find any *.go files, cannot continue
  ! looks like an error loading the chaincode or network, app will fail
  { name: 'load_chaincode() no chaincode',
  code: 400,
  details: 'did not find any *.go files, cannot continue' }
  ^C

**Comment by likepunk** [comment]
Never mind! I see app.js has also been changed to following:

```
                                           zip_url: 'https://github.com/ibm-blockchain/marbles/archive/v2.0.zip',
                                           unzip_dir: 'marbles-2.0/chaincode',
                                           git_url: 'http://gopkg.in/ibm-blockchain/marbles.v2/chaincode',
```

**Comment by dshuffma-ibm** [comment]
sorry for late reply. the Bluemix service now works with v0.6 hyperledger. there was some chaos as we added new branches to do the versioning. it looks like you figured it out anyway. can we close this?

**Comment by dshuffma-ibm** [comment]
closed, inactivity
